= Electrometeor - Build Desktop Applications With Electron + Meteor

:hp-tags: Meteor, Electron, JavaScript


Usually when you have an idea for a project, something is there standing in your way, trying to keep you from achieving your goal. An idea sparked in my mind a few months back for a desktop application but I could not find a simple way to achieve the goal of building that project. So what did I do? I gave up of course! Although not completely. The idea kept prompting me every couple weeks but I just ignored it. But this past week, with a lot of free time on my hands, I decided to give it a go.

But first, I needed to get over an initial hurdle. I want to build a desktop application _with Meteor_. I knew about Electron (formerly known as Atom-Shell) for creating desktop applications, but there werent many resources on integrating Meteor inside of Electron.

Electrometeor combines Electron and Meteor to allow you to easily create desktop applications that work both 100% offline & online.

Electrometeor creates an app that works offline and It uses node under the hood to allow you to access system modules. For example, one of the first things I tested was the node-applescript module which let me use applescript to create an Itunes controller that played/paused the song every 5 seconds.

Because Meteor is included, you can easily use DDP to connect to a web server if you want to sync data online.

As I mentioned, I created Electrometeor to scratch my own itch. I wanted a way to create desktop apps with Meteor. I have a project in mind that I will be starting soon that will use this.

Right now, Electrometeor is very simple. There are a lot of modules that Electron includes that will be helpful in the boilerplate. Prior to building this, I had no experience with Electron/Atom-Shell, so this is a learning experience for me. I want to continue to improve Electrometeor and make it the best desktop application boilerplate for Meteor developers. As I work on my project idea, I will be adding things that I think work well in a boilerplate. 

The good people at Kitematic are much to thank for Electrometeor. They had previously built a desktop app with Atom-Shell and Meteor so a lot of what I've done comes directly from their development of the Kitematic app.

I learned a lot about bash scripting by digging into their code and studying it one line at a time. Before, I thought bash scripts were scary but now I know how great they are.

I've also learned about the Meteor build tool. In the 5 or 6 months that I've been using Meteor, I've never had to use it before working on this project.

Inside Electron, it uses Node to start a child process that runs the Meteor build. This is all new information to me and I had to read a lot about child_process and all of the things it can do.

.Shoutouts:
- Kitematic - a lot of the code comes from an older version of their app

I want to give another shoutout to Kitematic. If it wasn't for them, I probably wouldn't have built Electrometeor.

Also, I want to give a shoutout to https://twitter.com/johnstonbl01[@johnstonbl01] for taking the time to edit this post, and thank you to everyone who took the time to read it!

If you have any questions, comments, or concerns, feel free to hit me up on Twitter: http://twitter.com/sircharlesw727[@SirCharlesW727]

Or you can join the gitter chat room to talk about Electrometeor there:
image:https://badges.gitter.im/Join%20Chat.svg[
"Electrometeor Gitter",
link="https://gitter.im/sircharleswatson/Electrometeor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]





Outline:

.What is it?
- A boilerplate using Electron and Meteor

.What does it do?
- allows you to work offline
- can access system libraries
- can use Meteor to connect to a web server

.Why did you create it?
- I've had a product idea in my mind for a while that I wanted to make.

.Where do you see it going?
- I want to expand it to include more of the options that Electron allows
- Want it to be the best desktop app boilerplate for Meteor

.What were some of the challenges you faced during development?
- Don't know a ton about bash scripting so I had to learn that to get the app to build
- Never used the meteor build tool
- never used child_process in node